# Generated by Django 3.1.6 on 2021-04-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demand_predict', '0003_auto_20210416_1815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='goods_demand',
        ),
    ]
