# Generated by Django 3.1.6 on 2021-04-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demand_predict', '0004_delete_goods_demand'),
    ]

    operations = [
        migrations.CreateModel(
            name='past_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_List', models.TextField(null=True)),
            ],
        ),
    ]
