# Generated by Django 3.1.6 on 2021-04-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand_predict', '0005_past_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='past_data',
            name='good_name',
            field=models.TextField(null=True),
        ),
    ]
