# Generated by Django 3.1.6 on 2021-04-20 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demand_predict', '0006_past_data_good_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='past_data',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='past_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
