# Generated by Django 3.1.6 on 2021-04-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand_predict', '0007_past_data_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='past_data',
            name='place',
            field=models.TextField(null=True),
        ),
    ]
