# Generated by Django 3.1.6 on 2021-04-20 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csvs', '0002_csv_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv',
            name='file_type',
            field=models.CharField(choices=[('raw material purchase', 'RAW MATERIAL PURCHASE'), ('goods demand', 'GOODS DEMAND'), ('raw material', 'RAW MATERIAL')], default='------', max_length=100),
        ),
        migrations.AlterField(
            model_name='csv',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uplo', to='auth.user'),
        ),
    ]
