# Generated by Django 3.1.6 on 2021-04-20 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csvs', '0003_auto_20210420_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uplo', to=settings.AUTH_USER_MODEL),
        ),
    ]
