# Generated by Django 3.1.6 on 2021-04-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0004_auto_20210420_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv',
            name='file_type',
        ),
    ]
