# Generated by Django 3.1.6 on 2021-04-21 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0010_goods_demand'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=220)),
                ('periods', models.PositiveIntegerField()),
                ('level_sc', models.DecimalField(decimal_places=5, max_digits=15)),
                ('trend_sc', models.DecimalField(decimal_places=5, max_digits=15)),
                ('seasonal_factor_sc', models.DecimalField(decimal_places=5, max_digits=15)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
