# Generated by Django 3.1.6 on 2021-04-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_company_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='level_sc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='seasonal_factor_sc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='trend_sc',
            field=models.FloatField(),
        ),
    ]
