# Generated by Django 3.1.6 on 2021-04-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_auto_20210421_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_demand',
            name='place',
            field=models.CharField(default='rayachoty', max_length=220),
        ),
    ]
