# Generated by Django 3.1.6 on 2021-04-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210313_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='standard_deviation',
            field=models.DecimalField(blank=True, decimal_places=3, default='5', max_digits=10, null=True),
        ),
    ]
